erDiagram

FUNCIONARIOS{
    
}

PESSOA_FISICA{

}

PESSOA_JURIDICA{

}

VISITANTE{}
VISITA{}
MORADOR{}
BLOCO{}
EDIFICIO{}
APARTAMENTO{}
VEICULO{}
SOLICITACAO_SERVICO{}

FUNCIONARIOS }O--|| FUNCIONARIOS:"GERENCIAM"
FUNCIONARIOS ||--O| PESSOA_FISICA:"É"
VISITANTE }|--O{ VISITA:""
PESSOA_FISICA o|--|| MORADOR:"É"
PESSOA_JURIDICA o|--|| MORADOR:"É"
BLOCO O|--|{ EDIFICIO:""
PESSOA_FISICA o|--|| VISITANTE:"É"
SOLICITACAO_SERVICO }O--|{ FUNCIONARIOS:""
EDIFICIO_SOLICITACAO_SERVICO }O--O{ EDIFICIO:""
SOLICITACAO_SERVICO }O--O{ EDIFICIO_SOLICITACAO_SERVICO:""
APARTAMENTO }|--O{ MORADOR:""
EDIFICIO ||--|{ APARTAMENTO:""
APARTAMENTO ||--O{ VEICULO:""
APARTAMENTO }|--O{ VISITA:""

























