erDiagram

PESSOA {
    CODIGO INT PK "NOT NULL"
    EMAIL STRING "NOT NULL"
    TELEFONE STRING "NOT NULL"
}

FUNCIONARIOS{
    CODIGO_FUNCIONARIO INT PK "NOT NULL"
    CARGO STRING "NOT NULL"
    GESTOR_DIRETO INT "NOT NULL"    
}

PESSOA_FISICA{
    CPF STRING PK "NOT NULL"
    NOME STRING "NOT NULL"
    DATA_NASCIMENTO DATE "NOT NULL"
}

PESSOA_JURIDICA{
    CNPJ STRING PK "NOT NULL"
    RAZAO_SOCIAL STRING "NOT NULL"
    NOME_FANTASISTA STRING "NOT NULL"
}

VISITANTE{
    CODIGO_VISITANTE INT PK "NOT NULL"
    VAI_PERNOITAR STRING  "NOT NULL"
}
MORADOR{
    EH_INQUILINO BOOLEAN "NOT NULL"
}
BLOCO{
    CODIGO_BLOCO INT PK "NOT NULL"
    QTD_EDIFICIOS INT "NOT NULL"
    LOCALIZACAO STRING "NOT NULL"
}
EDIFICIO{
    CODIGO_EDIFICIO INT PK "NOT NULL"
    NOME_EDIFICIO STRING "NOT NULL"
    QTD_APARTAMENTOS INT "NOT NULL"
}
APARTAMENTO{
    CODIGO_APARTAMENTO INT PK "NOT NULL"
    CODIGO_TIPO_APARTAMENTO INT "NOT NULL"
    ANDAR INT "NOT NULL"
}
VEICULO{
    CODIGO_VEICULO INT PK "NOT NULL"
    MODELO STRING "NOT NULL"
    ANO_FABRICACAO DATE "NOT NULL"
    TIPO_COMBUSTIVEL STRING "NOT NULL"
    MARCA STRING "NOT NULL"
    PLACA STRING "NOT NULL"
}
SOLICITACAO_SERVICO{
    CODIGO_SOLICITACAO INT PK "NOT NULL"
    TIPO_SERVICO STRING "NOT NULL"
}

SOLICITACAO_SERVICO_EDIFICIO{
    CODIGO_SOLICITACAO INT PK,FK "NOT NULL"
    CODIGO_EDIFICIO INT PK,FK "NOT NULL"
}

SOLICITACAO_SERVICO_APARTAMENTO{
    CODIGO_SOLICITACAO INT PK,FK "NOT NULL"
    CODIGO_APARTAMENTO INT PK,FK "NOT NULL"
}

SOLICITACAO_SERVICO_FUNCONARIO{
    CODIGO_FUNCIONARIO INT PK,FK "NOT NULL"
    CODIGO_SOLICITACAO INT PK,FK "NOT NULL"
}

SOLICITACAO_SERVICO_MORADOR{
    CPF_MORADOR STRING PK,FK "NOT NULL"
    CODIGO_SOLICITACAO INT PK,FK "NOT NULL"
}

MORADOR_APARTAMENTO{
    CODIGO_APARTAMENTO INT PK,FK "NOT NULL"
    CODIGO MORADOR PK,FK "NOT NULL" 
}

VISITA{
    CODIGO_VISITANTE INT PK,FK "NOT NULL"
    CODIGO_APARTAMENTO INT  PK,FK "NOT NULL"
    NUMERO_CARTAO_VISITANTE INT "NOT NULL"
    QTD_PERNOITE INT "NOT NULL"
}




PESSOA ||--O| PESSOA_FISICA : "é"
PESSOA ||--O| PESSOA_JURIDICA : "é"
FUNCIONARIOS }O--|| FUNCIONARIOS:"GERENCIAM"
FUNCIONARIOS }|--O{ SOLICITACAO_SERVICO_FUNCONARIO:""
SOLICITACAO_SERVICO_FUNCONARIO }O--O{ SOLICITACAO_SERVICO:""
VISITANTE }|--O{ VISITA:""
PESSOA_FISICA o|--|| MORADOR:"É"
PESSOA_FISICA O|--|| FUNCIONARIOS:"É"
PESSOA_JURIDICA o|--|| MORADOR:"É"
SOLICITACAO_SERVICO }O--O{ SOLICITACAO_SERVICO_MORADOR:""
SOLICITACAO_SERVICO_MORADOR }O--O{ MORADOR:""
BLOCO O|--|{ EDIFICIO:""
PESSOA_FISICA o|--|| VISITANTE:"É"
SOLICITACAO_SERVICO_EDIFICIO }O--O{ EDIFICIO:""
SOLICITACAO_SERVICO }O--O{ SOLICITACAO_SERVICO_EDIFICIO:""
APARTAMENTO }|--O{ MORADOR_APARTAMENTO:""
MORADOR_APARTAMENTO }O--O{MORADOR:""
SOLICITACAO_SERVICO }O--O{ SOLICITACAO_SERVICO_APARTAMENTO:""
SOLICITACAO_SERVICO_APARTAMENTO }O--O{ APARTAMENTO:""
EDIFICIO ||--|{ APARTAMENTO:""
APARTAMENTO ||--O{ VEICULO:""
APARTAMENTO }|--O{ VISITA:""