erDiagram

PEDIDO{
    DATA DATE "NOT NULL"
    HORA TIME "NOT NULL"
    CLIENTE CLIENTE "NOT NULL"
    PRODUTO PRODUTO "NOT NULL"
    QUANTIDADE INT "NOT NULL"
}

CLIENTE{
    NOME STRING "NOT NULL"
    EMAIL STRING "NOT NULL"
    TELEFONE STRING "NOT NULL"
    ENDERECO STRING "NOT NULL"
}

PRODUTO{
    NOME STRING "NOT NULL"
    DESCRICAO STRING "NOT NULL"
    PRECO FLOAT "NOT NULL"
    IMAGEM IMAGE "NOT NULL"
}

FORNECEDOR {
    NOME STRING "NOT NULL"
    ENDERECO STRING "NOT NULL"
    EMAIL STRING "NOT NULL"
    TELEFONE STRING "NOT NULL"
}

PAGAMENTO {
    DATA DATE "NOT NULL"
    HORA TIME "NOT NULL"
    VALOR FLOAT "NOT NULL"
    CLIENTE CLIENTE "NOT NULL"
    CARTAO_CREDITO STRING "NOT NULL"
}


PEDIDO }|--|| CLIENTE : "FAZ"
PEDIDO}|--|| FORNECEDOR : "FORNECE"
PEDIDO ||--O| PAGAMENTO : "GERA"
PEDIDO ||--}| PRODUTO : "INCLUI"