erDiagram

JOGADORES{
    ID INT PK "NOT NULL"
    NOME STRING "NOT NULL"
    DT_NASCIMENTO STRING "NOT NULL"
    NIVEL INT  "NOT NULL"
}

CONQUISTAS{
    ID INT PK "NOT NULL"
    NOME STRING "NO NULL"
    DESCRICAO STRING "NOT NULL"
}

PERSONAGEM{
    ID INT PK "NOT NULL"
    JOGADOR  JOGADOR FK "NOT NULLL"
    ARMA ARMA FK "NOT NULL"
}

MISSOES {
    ID INT PK "NOT NULL"
    NOME STRING "NOT NULL"
    DIFICULDADE STRING "NOT NULL"
    RECOMPENSA STRING "NOT NULL" 
}

ARMAS{
    ID  INT PK "NOT NULL"
    NOME STRING "NOT NULL"
    TIPO STRING  "NOT NULL"
    DANO SHORT  "NOT NULL"
}

INVENTARIOS{
    ID INT PK "NOT NULL"
    JOGADOR JOGADOR "NOT NULL"
    ARMA ARMA "NOT NULL"
}

CONQUISTAS_JOGADORES{
    ID_CONQUISTAS INT PK,FK "NOT NULL"
    ID_JOGADORES INT PK,FK "NOT NULL"
}

JOGADORES_MISSOES{
    ID_JOGADORES INT PK,FK "NOT NULL"
    ID_MISSOES INT PK,FK "NOT NULL"
}

PERSONAGENS_ARMA{
    ID_PERSONAGEM INT PK,FK "NOT NULL"
    ID_ARMA INT PK,FK "NOT NULL"
}

    JOGADORES }|--|{CONQUISTAS_JOGADORES:""
    CONQUISTAS }O--|{CONQUISTAS_JOGADORES:""
    JOGADORES ||--|{ INVENTARIOS : ""
    JOGADORES }|--O{ CONQUISTAS:"" 
    JOGADORES }|--O{ PERSONAGEM:""  
    JOGADORES ||--O{ MISSOES:""
    PERSONAGEM }O--O{ ARMAS:""
    JOGADORES }|--|{ JOGADORES_MISSOES:""
    MISSOES }O--|{ JOGADORES_MISSOES:""
    PERSONAGEM }O--O{ PERSONAGENS_ARMA:""
    ARMAS }O--O{ PERSONAGENS_ARMA:""