erDiagram
EMPRESA_COMPRADORA{
    ID_EMPRESA INT PK,FK "NOT NULL"
}

VENDA{
    ID_VENDA INT PK "NOT NULL"
    DATA_VENDA DATE "NOT NULL"
}
TIPO_VINHO{
    ID_VINHO STRING PK "NOT NULL"
    NOME STRING "NOT NULL"
    DESCRICAO STRING "NOT NULL"
}

MARCA_VINHO{
    ID_MARCA_VINHO STRING PK "NOT NULL"
    NOME STRING PK "NOT NULL"
    TIPO INT "NOT NULL"
}

MARCA_TIPO_VINHO{
    ID_MARCA_VINHO STRING PK,FK "NOT NULL"
    ID_VINHO STRING PK,FK "NOT NULL"
}
EMPRESA{
    ID_EMPRESA INT PK "NOT NULL"
    RAZAO_SOCIAL STRING "NOT NULL"
    ENDERECO STRING "NOT NULL"
    TELEFONE STRING "NOT NULL"
}


SAFRA{
    ID_SAFRA INT PK "NOT NULL"
    ANO INT "NOT NULL"
    DESCRICAO STRING "NOT NULL"
    QTD_VINHO_PRODUZIDO FLOAT "NOT NULL"
}

ITEM_VENDA{
    ID_SAFRA INT PK,FK "NOT NULL"
    ID_VENDA INT PK,FK "NOT NULL"
    QTD_VENDIDA FLOAT "NOT NULL"
}

COTA_SAFRA{
    ID_SAFRA INT PK,FK "NOT NULL"
    ID_EMPRESA_PRESTADORA_SERVICO INT PK,FK "NOT NULL"
    QTD_ESTIPULADA FLOAT "NOT NULL"
}

LOCAL_PLANTIO{
    ID_LOCAL_PLANTIO INT PK "NOT NULL" 
    NOME STRING "NOT NULL"
    AREA FLOAT "NOT NULL"
    DESCRICAO STRING "NOT NULL"
}

PLANTACAO{
    ID_VINHO INT PK,FK "NOT NULL"
    ID_LOCAL_PLANTIO INT PK,FK "NOT NULL"
    DATA_INI DATE "NOT NULL"
    DATA-FIM  DATE "NOT NULL"
}

GERENCIA_LOCAL{
    ID_EMPRESA_PRESTADORA_SERVICO INT PK,FK "NOT NULL"
    ID_LOCAL_PLANTIO INT PK,FK "NOT NULL"
    DATA_INI DATE "NOT NULL"
    DATA-FIM  DATE "NOT NULL"
}


EMPRESA_PRESTADORA_SERVICO{
    ID_EMPRESA INT PK,FK "NOT NULL"
    ID_EMPRESA_PRESTADORA_SERVICO INT PK "NOT NULL"
    PESSOA_CONTATO STRING "NOT NULL"
    TIPO_PRESTACAO_SERVICO STRING "NOT NULL"
}

TIPO_VINHO }o--o{ PLANTACAO :""
PLANTACAO }o--o{ LOCAL_PLANTIO:""
LOCAL_PLANTIO }o--o{ GERENCIA_LOCAL:""
GERENCIA_LOCAL }o--o{ EMPRESA_PRESTADORA_SERVICO:""
EMPRESA_PRESTADORA_SERVICO }o--o{ COTA_SAFRA:""
COTA_SAFRA }o--o{ SAFRA:""
SAFRA }o--|{ ITEM_VENDA:""
ITEM_VENDA }O--|{ VENDA:""
SAFRA ||--O{ MARCA_VINHO:""
MARCA_VINHO }|--O{ MARCA_TIPO_VINHO:""
MARCA_TIPO_VINHO }|--O{ TIPO_VINHO:""
EMPRESA ||--O| EMPRESA_PRESTADORA_SERVICO:""
EMPRESA ||--O| EMPRESA_COMPRADORA:""
EMPRESA_PRESTADORA_SERVICO }O--|| VENDA:""
EMPRESA_COMPRADORA }O--|| VENDA:""
